services:
  - type: web
    name: votesecure
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false

databases:
  - name: votesecure-db
    plan: free
    databaseName: voting_system
    user: votesecure
